baseURL = 'http://pcphysclub.github.io/'
languageCode = 'en-us'
title = 'Physics Club'
theme = 'paper'

[params]
  # color style
  color = 'linen'                           # linen, wheat, gray, light

  # header social icons
  github = 'pcphysclub'                 # github.com/YOUR_GITHUB_ID
  
  favicon = true

  # misc
  math = true                               # enable KaTeX math typesetting globally
